/**
 * Neo4j Configuration Manager
 *
 * Handles Neo4j connection configuration for grasp-it skills.
 * Supports multiple connection types: driver (neo4j-driver), cypher-shell, and MCP.
 *
 * Configuration is stored per-project in a `.env` file at the project root.
 * A global config at ~/.grasp-it/ can be used for shared credentials.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, appendFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { homedir } from "node:os";

export const NEO4J_CONFIG_FILE = ".env";
export const GLOBAL_CONFIG_DIR = ".grasp-it";
export const GLOBAL_CONFIG_FILE = "neo4j.env";

// Environment variable names
export const ENV_VARS = {
  URI: "NEO4J_URI",
  DATABASE: "NEO4J_DATABASE",
  USERNAME: "NEO4J_USERNAME",
  PASSWORD: "NEO4J_PASSWORD",
  CONNECTION_TYPE: "NEO4J_CONNECTION_TYPE",
} as const;

// Connection type options
export type ConnectionType = "driver" | "cypher-shell" | "mcp";

// Default values
export const DEFAULTS = {
  DATABASE: "neo4j",
  CONNECTION_TYPE: "driver" as ConnectionType,
  URI: "bolt://localhost:7687",
  USERNAME: "neo4j",
};

/**
 * Neo4j configuration object
 */
export interface Neo4jConfig {
  uri: string;
  database: string;
  username: string;
  password: string;
  connectionType: ConnectionType;
}

/**
 * Result of loading configuration
 */
export interface ConfigLoadResult {
  success: boolean;
  config?: Neo4jConfig;
  error?: string;
  source?: "project" | "global" | "environment" | "none";
}

/**
 * Parse a .env file content and return key-value pairs
 */
function parseEnvFile(content: string): Record<string, string> {
  const result: Record<string, string> = {};
  const lines = content.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();
    // Skip empty lines and comments
    if (!trimmed || trimmed.startsWith("#")) continue;
    // Parse KEY=VALUE
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex > 0) {
      const key = trimmed.slice(0, eqIndex).trim();
      let value = trimmed.slice(eqIndex + 1).trim();
      // Remove surrounding quotes if present
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      result[key] = value;
    }
  }

  return result;
}

/**
 * Serialize a config object to .env file format
 */
function serializeEnvFile(config: Neo4jConfig): string {
  const lines = [
    `# Neo4j Configuration for grasp-it`,
    `# Generated by grasp-it plugin`,
    `# Do not commit this file to version control`,
    "",
    `${ENV_VARS.URI}=${config.uri}`,
    `${ENV_VARS.DATABASE}=${config.database}`,
    `${ENV_VARS.USERNAME}=${config.username}`,
    `${ENV_VARS.PASSWORD}=${config.password}`,
    `${ENV_VARS.CONNECTION_TYPE}=${config.connectionType}`,
    "",
  ];
  return lines.join("\n");
}

/**
 * Check if environment variables are set (for deployment/CI scenarios)
 */
function hasEnvironmentVars(): boolean {
  return Boolean(
    process.env[ENV_VARS.URI] &&
    process.env[ENV_VARS.USERNAME] &&
    process.env[ENV_VARS.PASSWORD]
  );
}

/**
 * Load config from environment variables
 */
function loadFromEnvironment(): Neo4jConfig | null {
  if (!hasEnvironmentVars()) return null;

  return {
    uri: process.env[ENV_VARS.URI] || DEFAULTS.URI,
    database: process.env[ENV_VARS.DATABASE] || DEFAULTS.DATABASE,
    username: process.env[ENV_VARS.USERNAME] || DEFAULTS.USERNAME,
    password: process.env[ENV_VARS.PASSWORD] || "",
    connectionType: (process.env[ENV_VARS.CONNECTION_TYPE] as ConnectionType) || DEFAULTS.CONNECTION_TYPE,
  };
}

/**
 * Load config from a .env file at a given path
 */
function loadFromEnvFile(filePath: string): Neo4jConfig | null {
  if (!existsSync(filePath)) return null;

  try {
    const content = readFileSync(filePath, "utf-8");
    const vars = parseEnvFile(content);

    // Check if required vars are present
    if (!vars[ENV_VARS.URI] || !vars[ENV_VARS.USERNAME]) return null;

    return {
      uri: vars[ENV_VARS.URI] || DEFAULTS.URI,
      database: vars[ENV_VARS.DATABASE] || DEFAULTS.DATABASE,
      username: vars[ENV_VARS.USERNAME] || DEFAULTS.USERNAME,
      password: vars[ENV_VARS.PASSWORD] || "",
      connectionType: (vars[ENV_VARS.CONNECTION_TYPE] as ConnectionType) || DEFAULTS.CONNECTION_TYPE,
    };
  } catch {
    return null;
  }
}

/**
 * Find the global config directory path (~/.grasp-it/)
 */
function getGlobalConfigPath(): string {
  return join(homedir(), GLOBAL_CONFIG_DIR, GLOBAL_CONFIG_FILE);
}

/**
 * Load Neo4j configuration with fallback chain:
 * 1. Environment variables (highest priority for CI/deployment)
 * 2. Project-level .env file
 * 3. Global ~/.grasp-it/neo4j.env file
 */
export function loadConfig(projectRoot: string): ConfigLoadResult {
  // 1. Check environment variables first
  const fromEnv = loadFromEnvironment();
  if (fromEnv) {
    return { success: true, config: fromEnv, source: "environment" };
  }

  // 2. Check project-level .env file
  const projectEnvPath = join(projectRoot, NEO4J_CONFIG_FILE);
  const fromProject = loadFromEnvFile(projectEnvPath);
  if (fromProject) {
    return { success: true, config: fromProject, source: "project" };
  }

  // 3. Check global config
  const globalPath = getGlobalConfigPath();
  const fromGlobal = loadFromEnvFile(globalPath);
  if (fromGlobal) {
    return { success: true, config: fromGlobal, source: "global" };
  }

  return {
    success: false,
    error: "No Neo4j configuration found",
    source: "none",
  };
}

/**
 * Ensure .env is listed in .gitignore so credentials are not committed.
 * Appends the entry only if it is not already present.
 */
export function ensureEnvInGitignore(projectRoot: string): void {
  const gitignorePath = join(projectRoot, ".gitignore");
  const entry = ".env";
  if (existsSync(gitignorePath)) {
    const content = readFileSync(gitignorePath, "utf-8");
    const lines = content.split("\n").map((l) => l.trim());
    if (lines.includes(entry)) return; // already present
    appendFileSync(gitignorePath, `\n# Added by grasp-it — keep Neo4j credentials out of version control\n${entry}\n`, "utf-8");
  } else {
    writeFileSync(gitignorePath, `# Added by grasp-it — keep Neo4j credentials out of version control\n${entry}\n`, "utf-8");
  }
}

/**
 * Save configuration to a .env file and ensure .env is in .gitignore.
 */
export function saveConfig(projectRoot: string, config: Neo4jConfig): void {
  const filePath = join(projectRoot, NEO4J_CONFIG_FILE);
  const content = serializeEnvFile(config);
  writeFileSync(filePath, content, "utf-8");
  ensureEnvInGitignore(projectRoot);
}

/**
 * Save global configuration (~/.grasp-it/neo4j.env)
 */
export function saveGlobalConfig(config: Neo4jConfig): void {
  const dir = join(homedir(), GLOBAL_CONFIG_DIR);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  const filePath = join(dir, GLOBAL_CONFIG_FILE);
  const content = serializeEnvFile(config);
  writeFileSync(filePath, content, "utf-8");
}

/**
 * Check if configuration exists (any source)
 */
export function hasConfig(projectRoot: string): boolean {
  const result = loadConfig(projectRoot);
  return result.success;
}

/**
 * Get the required config keys for prompting user
 */
export function getRequiredConfigKeys(): string[] {
  return [ENV_VARS.URI, ENV_VARS.DATABASE, ENV_VARS.USERNAME, ENV_VARS.PASSWORD];
}

/**
 * Build a cypher-shell command string from config
 */
export function buildCypherShellCommand(
  config: Neo4jConfig,
  query: string
): { command: string; args: string[] } {
  const args = [
    "-a", config.uri,
    "-u", config.username,
    "-p", config.password,
    "-d", config.database,
    "--format", "plain",
  ];

  if (query) {
    return { command: "cypher-shell", args: [...args, query] };
  }

  return { command: "cypher-shell", args };
}

/**
 * Get connection type description for user prompts
 */
export function getConnectionTypeDescription(type: ConnectionType): string {
  switch (type) {
    case "driver":
      return "Direct Neo4j driver connection (requires neo4j-driver package)";
    case "cypher-shell":
      return "Neo4j CLI tool (cypher-shell) - works with Neo4j Desktop, Aura, and self-managed";
    case "mcp":
      return "Model Context Protocol - connects via neo4j-mcp server";
  }
}

/**
 * Prompt questions for first-use setup
 */
export const SETUP_PROMPTS = {
  CONNECTION_TYPE: `Which connection type would you like to use?

  1. Driver (default) - Direct connection using neo4j-driver.
     Best for programmatic access. Requires Node.js integration.

  2. cypher-shell - Use Neo4j CLI tool. Works with Neo4j Desktop, Aura, and self-managed.
     Suitable for most users. Requires Neo4j CLI to be installed.

  3. MCP (Model Context Protocol) - Connect via neo4j-mcp server.
     Works with all Neo4j deployment types. Requires neo4j-mcp binary.

Enter your choice (1, 2, or 3) or press Enter for default (1 - Driver):`,

  NEO4J_URI: `Enter your Neo4j connection URI:

  - Local: bolt://localhost:7687
  - Neo4j Aura: neo4j+s://xxxxx.databases.neo4j.io
  - Custom: bolt://hostname:7687

Press Enter for default (bolt://localhost:7687):`,

  NEO4J_DATABASE: `Enter the database name:

Press Enter for default (neo4j):`,

  NEO4J_USERNAME: `Enter your Neo4j username:

Press Enter for default (neo4j):`,

  NEO4J_PASSWORD: `Enter your Neo4j password:`,

  USE_GLOBAL_CONFIG: `Would you like to use a global config for this connection?

  - Yes: Store credentials in ~/.grasp-it/neo4j.env (shared across all projects)
  - No: Store credentials in this project's .env file (project-specific)

Enter yes/no or press Enter for default (no):`,
} as const;